# Generated by Django 5.2.1 on 2025-06-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The title of the blog post', max_length=200, null=True)),
                ('date', models.DateTimeField(blank=True, help_text='The publication date and time of the blog post', null=True)),
                ('image', models.ImageField(blank=True, help_text='Featured image for the blog post', null=True, upload_to='blog_images/')),
                ('author_name', models.CharField(blank=True, help_text='The name of the blog post author', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='The content or description of the blog post', null=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The main title of the hero section', max_length=200, null=True)),
                ('short_description', models.TextField(blank=True, help_text='A brief description for the hero section', null=True)),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the hero section', null=True, upload_to='hero_images/')),
                ('card1_title', models.CharField(blank=True, help_text='Title for the first card in the hero section', max_length=100, null=True)),
                ('card1_description', models.TextField(blank=True, help_text='Description for the first card', null=True)),
                ('card2_title', models.CharField(blank=True, help_text='Title for the second card in the hero section', max_length=100, null=True)),
                ('card2_description', models.TextField(blank=True, help_text='Description for the second card', null=True)),
                ('card3_title', models.CharField(blank=True, help_text='Title for the third card in the hero section', max_length=100, null=True)),
                ('card3_description', models.TextField(blank=True, help_text='Description for the third card', null=True)),
                ('welcome_image', models.ImageField(blank=True, help_text='Image for the welcome section', null=True, upload_to='welcome_images/')),
                ('welcome_video', models.FileField(blank=True, help_text='Video file for the welcome section', null=True, upload_to='welcome_videos/')),
                ('welcome_title', models.CharField(blank=True, help_text='Title for the welcome section', max_length=200, null=True)),
                ('welcome_subtitle', models.CharField(blank=True, help_text='Subtitle for the welcome section', max_length=200, null=True)),
                ('welcome_description', models.TextField(blank=True, help_text='Detailed description for the welcome section', null=True)),
                ('welcome_video_short_description', models.CharField(blank=True, help_text='Short description for the welcome video', max_length=200, null=True)),
                ('service_title', models.CharField(blank=True, help_text='service title', max_length=200, null=True)),
                ('service_description', models.CharField(blank=True, help_text='Short description for the service section', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='JinnoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='The contact email address for the company', max_length=254, null=True)),
                ('facebook_link', models.URLField(blank=True, help_text="URL to the company's Facebook page", null=True)),
                ('x_link', models.URLField(blank=True, help_text="URL to the company's X profile", null=True)),
                ('instagram_link', models.URLField(blank=True, help_text="URL to the company's Instagram profile", null=True)),
                ('website_link', models.URLField(blank=True, help_text="URL to the company's official website", null=True)),
                ('company_name', models.CharField(blank=True, help_text='The official name of the company', max_length=100, null=True)),
                ('company_logo', models.ImageField(blank=True, help_text="The company's logo image", null=True, upload_to='company_logos/')),
                ('slogan', models.CharField(blank=True, help_text="The company's slogan or tagline", max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, help_text="The company's contact phone number", max_length=20, null=True)),
                ('location', models.CharField(blank=True, help_text='The physical address or location of the company', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Jinno Setting',
                'verbose_name_plural': 'Jinno Settings',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Image representing the project', null=True, upload_to='project_images/')),
                ('category', models.CharField(blank=True, help_text='Category or type of the project', max_length=100, null=True)),
                ('title', models.CharField(blank=True, help_text='Title of the project', max_length=200, null=True)),
                ('location', models.CharField(blank=True, help_text='Location where the project was executed', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the project', null=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='SectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_hero_section_image', models.ImageField(blank=True, help_text='Hero section image for the blog page', null=True, upload_to='hero_images/blog/')),
                ('project_hero_section_image', models.ImageField(blank=True, help_text='Hero section image for the project page', null=True, upload_to='hero_images/project/')),
                ('service_hero_section_image', models.ImageField(blank=True, help_text='Hero section image for the service page', null=True, upload_to='hero_images/service/')),
                ('contact_hero_section_image', models.ImageField(blank=True, help_text='Hero section image for the contact page', null=True, upload_to='hero_images/contact/')),
            ],
            options={
                'verbose_name': 'Section Setting',
                'verbose_name_plural': 'Section Settings',
            },
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The main title of the services section', max_length=200, null=True)),
                ('short_description', models.TextField(blank=True, help_text='A brief description for the services section', null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the services offered', null=True)),
                ('image', models.ImageField(blank=True, help_text='Image representing the service', null=True, upload_to='services_images/')),
                ('icon', models.ImageField(blank=True, help_text='Icon for the service', null=True, upload_to='services_icons/')),
            ],
            options={
                'verbose_name': 'Services Section',
                'verbose_name_plural': 'Services Sections',
            },
        ),
        migrations.CreateModel(
            name='ServicesSectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The main title of the services section', max_length=200, null=True)),
                ('short_description', models.TextField(blank=True, help_text='A brief description for the services section', null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the services offered', null=True)),
                ('projects_completed', models.PositiveIntegerField(blank=True, help_text='Number of projects completed', null=True)),
                ('happy_customers', models.PositiveIntegerField(blank=True, help_text='Number of satisfied customers', null=True)),
                ('card_image', models.ImageField(blank=True, help_text='Image for the service card', null=True, upload_to='services_card_images/')),
            ],
            options={
                'verbose_name': 'Services Section Two',
                'verbose_name_plural': 'Services Sections Two',
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='Full name of the person providing the testimony', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='The testimonial content or description', null=True)),
                ('image', models.ImageField(blank=True, help_text='Image of the person providing the testimony', null=True, upload_to='testimony_images/')),
                ('post', models.CharField(blank=True, help_text='Job title or position of the person providing the testimony', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Testimony',
                'verbose_name_plural': 'Testimonies',
            },
        ),
    ]
