# Generated by Django 5.2.1 on 2025-06-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jinnosetting',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='URL for the Google Maps embed iframe', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='jinnosetting',
            name='company_name',
            field=models.CharField(blank=True, help_text='The official name of the company', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jinnosetting',
            name='instagram_link',
            field=models.URLField(blank=True, help_text="URL to the company's Instagram profile", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jinnosetting',
            name='slogan',
            field=models.CharField(blank=True, help_text="The company's slogan or tagline", max_length=1000, null=True),
        ),
    ]
