# Generated by Django 5.2.1 on 2025-06-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_quoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionsettings',
            name='about_hero_section_image',
            field=models.ImageField(blank=True, help_text='Hero section image for the about page', null=True, upload_to='hero_images/about/'),
        ),
    ]
