# Generated by Django 5.2.1 on 2025-06-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_sectionsettings_about_hero_section_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text="URL to the partner's logo image (preferably SVG or PNG with transparent background).", max_length=255, upload_to='', verbose_name='Logo URL')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='AboutStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Title for the stats section (e.g., 'Our Impact in Numbers').", max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Brief description of the stats section.', verbose_name='Description')),
                ('projects_completed', models.PositiveIntegerField(default=0, help_text='Number of projects completed.', verbose_name='Projects Completed')),
                ('client_satisfaction', models.PositiveIntegerField(default=0, help_text='Client satisfaction percentage (e.g., 98 for 98%).', verbose_name='Client Satisfaction')),
                ('team_members', models.PositiveIntegerField(default=0, help_text='Number of team members.', verbose_name='Team Members')),
                ('countries_served', models.PositiveIntegerField(default=0, help_text='Number of countries served.', verbose_name='Countries Served')),
            ],
            options={
                'verbose_name': 'Stats',
                'verbose_name_plural': 'Stats',
            },
        ),
        migrations.CreateModel(
            name='AboutStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_image', models.ImageField(blank=True, help_text="Upload an image representing the company's story (e.g., office or team).", null=True, upload_to='about_images/', verbose_name='Story Image')),
                ('title', models.CharField(blank=True, help_text="Main title for the story section (e.g., 'Building The Future Together').", max_length=200, verbose_name='Title')),
                ('short_description', models.TextField(blank=True, help_text="A brief overview of the company's story.", verbose_name='Short Description')),
                ('innovation', models.TextField(blank=True, help_text="Description of the company's innovation focus.", verbose_name='Innovation')),
                ('quality', models.TextField(blank=True, help_text="Description of the company's quality standards.", verbose_name='Quality')),
                ('vision', models.TextField(blank=True, help_text="The company's vision statement.", verbose_name='Vision')),
                ('mission', models.TextField(blank=True, help_text="The company's mission statement.", verbose_name='Mission')),
                ('values', models.TextField(blank=True, help_text="The company's core values.", verbose_name='Values')),
            ],
            options={
                'verbose_name': 'About Story',
                'verbose_name_plural': 'About Stories',
            },
        ),
        migrations.CreateModel(
            name='AboutTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Full name of the team member.', max_length=100, verbose_name='Name')),
                ('post', models.CharField(blank=True, help_text='Job title or role (e.g., CEO & Founder).', max_length=100, verbose_name='Position')),
                ('short_description', models.TextField(blank=True, help_text="Brief description of the team member's expertise or role.", verbose_name='Short Description')),
                ('image', models.ImageField(blank=True, help_text='Upload a profile image for the team member.', null=True, upload_to='team_images/', verbose_name='Profile Image')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
