# Generated by Django 5.2.1 on 2025-06-04 09:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_aboutpartner_aboutstats_aboutstory_aboutteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='The content or description of the blog post', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detailed description of the project', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicessectiontwo',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detailed description of the services offered', null=True),
        ),
    ]
