# Generated by Django 5.2.1 on 2025-06-13 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_theme_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='secondary_color',
            field=models.CharField(default='#fc5e28', help_text='Secondary color in hex format (e.g., #fc5e28)', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code.')]),
        ),
    ]
