# Generated by Django 5.2.1 on 2025-06-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_herosection_card1_image_herosection_card2_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False, help_text='Indicates whether the project is completed'),
        ),
    ]
