# Generated by Django 5.2.1 on 2025-06-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_project_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicessection',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique slug for the service URL', max_length=250, null=True, unique=True),
        ),
    ]
