# Generated by Django 5.2.1 on 2025-06-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_servicessection_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
